#!/usr/bin/env bash
function cleanup {
  echo "Removing work directory"
  rm -rf "$work_dir"
}

set -o errexit -o errtrace
trap cleanup INT ERR

startGGToken=${1:?'Missing required startGGToken'}
googleAuth=${2:?'Missing required googleAuth'}
spreadsheetName=${3:?'Missing required spreadsheetName'}
headToHeadWS=${4:?'Missing required headToHeadWS'}
allWinsLossesWS=${5:?'Missing required allWinsLossesWS'}
events=${6:?'Missing required events'}
playerSlugs=${7:?'Missing required playerSlugs'}

# create temp directory for key
work_dir=$(mktemp -d)
cert_json="$work_dir/google_cert.json"

#create cert_json
printf "%s" "$googleAuth" > "$cert_json"

#run python main
python main.py "$startGGToken" "$cert_json" "$spreadsheetName" "$headToHeadWS" "$allWinsLossesWS" "$events" "$playerSlugs"

cleanup