#!/usr/bin/env bash
function usage {
  [[ -n "$1" ]] && echo "$1"
  cat <<EOD

Usage: run-spreadsheet <startGGToken> <googleAuth> <spreadsheetName> <headToHeadWS> <allWinsLossesWS> <events> <playerSlugs>

This script gathers data from start.gg for a given set of players and set of events they participated in.
This data will be put into a google sheet specified by the user.

<startGGToken> Auth token from start.gg. Instructions on how to obtain one linked in README
<googleAuth> JSON authentication one lines and stringified. Instructions in README
<spreadsheetName> Name of the spreadsheet that you are writing the data to
<headToHeadWS> Name of the worksheet you are writing the head to head data to
<allWinsLossesWS> Name of the worksheet you are writing the all wins and losses data to
<events> List of all events you are getting data from
<playerSlugs> List of all player tags and corresponding slugs you are getting data for

EOD
  exit 1
}

[[ "$1" = -h ]] && usage

function note {
    echo ▶ $@ '...'
}

function cleanup {
  echo "Removing work directory"
  rm -rf "$work_dir"
}

set -o errexit -o errtrace
trap cleanup INT ERR

startGGToken=${1:?'Missing required startGGToken'}
googleAuth=${2:?'Missing required googleAuth'}
spreadsheetName=${3:?'Missing required spreadsheetName'}
headToHeadWS=${4:?'Missing required headToHeadWS'}
allWinsLossesWS=${5:?'Missing required allWinsLossesWS'}
events=${6:?'Missing required events'}
playerSlugs=${7:?'Missing required playerSlugs'}

# create temp directory for key
work_dir=$(mktemp -d)
cert_json="$work_dir/google_cert.json"

#create cert_json
printf "%s" "$googleAuth" > "$cert_json"

#run python main
python main.py "$startGGToken" "$cert_json" "$spreadsheetName" "$headToHeadWS" "$allWinsLossesWS" "$events" "$playerSlugs"

cleanup
