name: Create Matchup Spreadsheet
on:
    workflow_dispatch:
        inputs:
            startGGToken:
                description: startGGToken
                required: true
                type: string
            googleAuth:
                description: googleAuth
                required: true
                type: string
            spreadsheetName:
                description: spreadsheetName
                required: true
                type: string
            headToHeadWS:
                description: headToHeadWS
                required: true
                type: string
            allWinsLossesWS:
                description: allWinsLossesWS
                required: true
                type: string
            events:
                description: events
                required: true
                type: string
            playerSlugs:
                description: playerSlugs
                required: true
                type: string
            
jobs:
    write-spreadsheet:
        runs-on: ubuntu-20.04
        steps:
        -   name: Hide sensitive inputs
            uses: levibostian/action-hide-sensitive-inputs@1.0.0
        -   name: Checkout repo
            uses: actions/checkout@v4
        -   name: setup python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11' #install python version
                cache: 'pip'
        -   run: pip install -r requirements.txt
        -   name: gain permissions
            run: chmod +x .github/scripts/run-spreadsheet
        -   name: run script
            run: ./.github/scripts/run-spreadsheet "${{inputs.startGGToken}}" ${{inputs.googleAuth}} "${{inputs.spreadsheetName}}" "${{inputs.headToHeadWS}}" "${{inputs.allWinsLossesWS}}" "${{inputs.events}}" "${{inputs.playerSlugs}}"
        
        
